import type { OntologyCommitStorage } from "./commits"
import type { OntologyMaterializationStorage } from "./materializations"
import type { OntologyOutboxStorage } from "./outbox"
import type { OntologySourceStorage } from "./sources"

export type {
  EditOntologyCommitIntent,
  GetOntologyCommitByIdempotencyKeyInput,
  GetOntologyCommitByIdInput,
  GetOntologyCommitByOriginInput,
  ListOntologyCommitsInput,
  ListOntologyCommitsResult,
  OntologyCommitOriginSelector,
  OntologyCommitRecord,
  OntologyCommitRunSelector,
  OntologyCommitStorage,
  OntologyCommitWrite,
  ProjectionOntologyCommitIntent,
  TelemetryOntologyCommitIntent,
} from "./commits"
export type {
  ApplyMaterializationChunkInput,
  ApplyMaterializationResult,
  ExactEffectiveLinkDelete,
  ExactEffectiveLinkWrite,
  ExactEffectiveObjectDelete,
  ExactEffectiveObjectWrite,
  ExactEffectiveWrites,
  ExactLinkOverrideDelete,
  ExactLinkOverrideWrite,
  ExactObjectOverrideDelete,
  ExactObjectOverrideWrite,
  ExactOverrideWrites,
  ExactTimeseriesPointWrite,
  ExactTimeseriesWrites,
  ExpectedSourceRevision,
  ExpectedTimeseriesPointRevision,
  FinalizeMaterializationInput,
  MaterializationApplyPhase,
  MaterializationCardinalityOccupantWorkRecord,
  MaterializationCasState,
  MaterializationClassificationWorkRecord,
  MaterializationEventWorkRecord,
  MaterializationIncidentObjectWorkRecord,
  MaterializationLinkScopeState,
  MaterializationLinkState,
  MaterializationObjectExistence,
  MaterializationObjectExistenceWorkRecord,
  MaterializationObjectState,
  MaterializationPlanChunk,
  MaterializationPlanFinalization,
  MaterializationPlanHeader,
  MaterializationPlanWorkItem,
  MaterializationPlanWorkRecord,
  MaterializationSession,
  MaterializationStatePage,
  MaterializationStateRequestChunk,
  MaterializationWorkEntityKind,
  MaterializationWorkPage,
  MaterializationWorkRecord,
  OntologyMaterializationStorage,
  ReadMaterializationObjectExistenceInput,
  SourceActivationWrite,
  SourceReplacementLinkState,
  SourceReplacementObjectState,
  SourceReplacementStatePage,
  StageMaterializationWorkInput,
  StoredLinkOverride,
  StoredObjectOverride,
  StoredTelemetryPoint,
  StreamMaterializationStateInput,
  StreamMaterializationWorkInput,
  StreamSourceReplacementStateInput,
} from "./materializations"
export type {
  ClaimedOntologyOutboxRow,
  ClaimOntologyOutboxInput,
  CompleteOntologyOutboxLeaseInput,
  OntologyMaterializationEvent,
  OntologyMaterializationEventDraft,
  OntologyOutboxRecord,
  OntologyOutboxStorage,
  OntologyOutboxWrite,
  PurgePublishedOntologyOutboxInput,
  RescheduleOntologyOutboxLeaseInput,
} from "./outbox"
export type {
  AbandonSourceMaterializationCandidateInput,
  AbandonSourceMaterializationInput,
  AssertSourceMaterializationExecution,
  AssertSourceMaterializationExecutionInput,
  BeginSourceMaterializationInput,
  CleanupTerminalSourceMaterializationsInput,
  CleanupTerminalSourceMaterializationsResult,
  GetActiveOntologySourceInput,
  MarkSourceMaterializationReadyInput,
  OntologySourceMaterializationStatus,
  OntologySourceRecord,
  OntologySourceStorage,
  ReclaimSourceMaterializationInput,
  SourceMaterializationExecution,
  StageSourceAssertion,
  StageSourceRowsInput,
  StageSourceRowsResult,
  StoredSourceAssertion,
  StoredSourceLinkAssertion,
  StoredSourceObjectAssertion,
} from "./sources"

export interface OntologyStorage {
  readonly commits: OntologyCommitStorage
  readonly sources: OntologySourceStorage
  readonly materializations: OntologyMaterializationStorage
  readonly outbox: OntologyOutboxStorage
}
