export { lowerEditBatch } from "./normalize"
export type {
  EditablePropertyId,
  EditBatch,
  EditCreateProperties,
  EditObjectHandle,
  EditObjectProperties,
  EditObjectRef,
  EditObjectSetRecorder,
  EditOperation,
  EditUpdateProperties,
  LinkDeleteEdit,
  LinkResetEdit,
  LinkUpsertEdit,
  ObjectCreateEdit,
  ObjectDeleteEdit,
  ObjectResetEdit,
  ObjectRestoreEdit,
  ObjectUnsetEdit,
  ObjectUpdateEdit,
  RecordEditsContext,
  TypedEditObjectRef,
} from "./types"
