export interface ConnectorEntry {
  id: string
  name: string
  description: string
  category: "Marketing" | "Productivity" | "Business" | "Protocols" | "Other"
  package: string
  icon?: string
}

export const connectorCatalog: readonly ConnectorEntry[] = [
  {
    id: "google-ads",
    name: "Google Ads",
    description: "Manager accounts and campaign reporting",
    category: "Marketing",
    package: "google",
    icon: "googleads.svg",
  },
  {
    id: "meta",
    name: "Meta",
    description: "Facebook and Instagram Graph API",
    category: "Marketing",
    package: "meta",
    icon: "meta.svg",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    description: "Advertising and organic Page management",
    category: "Marketing",
    package: "linkedin",
    icon: "linkedin.svg",
  },
  {
    id: "tiktok",
    name: "TikTok",
    description: "Display, Business Organic, and Ads reporting",
    category: "Marketing",
    package: "tiktok",
    icon: "tiktok.svg",
  },
  {
    id: "google",
    name: "Google",
    description: "Drive, Calendar, Gmail, Sheets, Meet, and Analytics",
    category: "Productivity",
    package: "google",
    icon: "google.ico",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    description: "SharePoint files, Outlook mail, calendars, delta sync, and subscriptions",
    category: "Productivity",
    package: "microsoft",
    icon: "microsoft.ico",
  },
  {
    id: "notion",
    name: "Notion",
    description: "Pages, properties, and Markdown",
    category: "Productivity",
    package: "notion",
    icon: "notion.svg",
  },
  {
    id: "github",
    name: "GitHub",
    description: "Repositories, issues, and REST API",
    category: "Productivity",
    package: "github",
    icon: "github.svg",
  },
  {
    id: "stripe",
    name: "Stripe",
    description: "Customers, subscriptions, invoices, and payments",
    category: "Business",
    package: "stripe",
    icon: "stripe.svg",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    description: "CRM contacts, deals, and activities",
    category: "Business",
    package: "pipedrive",
    icon: "pipedrive.png",
  },
  {
    id: "teamleader",
    name: "Teamleader",
    description: "CRM, invoicing, and quotations",
    category: "Business",
    package: "teamleader",
    icon: "teamleader.ico",
  },
  {
    id: "pandadoc",
    name: "PandaDoc",
    description: "Documents and electronic signatures",
    category: "Business",
    package: "pandadoc",
    icon: "pandadoc.png",
  },
  {
    id: "pennylane",
    name: "Pennylane",
    description: "Quotes, products, and customers",
    category: "Business",
    package: "pennylane",
    icon: "pennylane.ico",
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    description: "Accounting reads and writes, receipts, and change data capture",
    category: "Business",
    package: "quickbooks",
  },
  {
    id: "mercury",
    name: "Mercury",
    description: "Banking, transactions, and invoicing",
    category: "Business",
    package: "mercury",
    icon: "mercury.svg",
  },
  {
    id: "unipile",
    name: "Unipile",
    description: "Messaging and LinkedIn outreach",
    category: "Business",
    package: "unipile",
    icon: "unipile.png",
  },
  {
    id: "companycam",
    name: "CompanyCam",
    description: "Projects and jobsite photos",
    category: "Other",
    package: "companycam",
    icon: "companycam.png",
  },
  {
    id: "ace-iot",
    name: "ACE IoT",
    description: "Sites, BACnet points, gateways, and time series",
    category: "Other",
    package: "ace-iot",
    icon: "ace-iot.ico",
  },
  {
    id: "exa",
    name: "Exa",
    description: "Web search and page contents",
    category: "Other",
    package: "exa",
    icon: "exa.png",
  },
  {
    id: "rest",
    name: "REST",
    description: "HTTP APIs with authentication, pacing, and retries",
    category: "Protocols",
    package: "rest",
  },
  {
    id: "sql",
    name: "SQL",
    description: "PostgreSQL, MySQL, and SQLite",
    category: "Protocols",
    package: "sql",
  },
  {
    id: "sftp",
    name: "SFTP",
    description: "Read, write, and stream remote files",
    category: "Protocols",
    package: "sftp",
  },
  {
    id: "imap",
    name: "IMAP",
    description: "Read mailboxes, messages, and MIME parts",
    category: "Protocols",
    package: "imap",
  },
]
