import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { createElement } from "react"
import { renderToStaticMarkup } from "react-dom/server"
import { FrameworkStack } from "../components/FrameworkStack"

// Run from the repo root: bun --filter @sixb/docs generate:readme
const root = resolve(import.meta.dir, "../../../..")
const source = renderToStaticMarkup(
  createElement(FrameworkStack, { activeLayer: null, phase: "ready" })
)
const css = await readFile(resolve(root, "apps/docs/src/components/homeWalkthrough.css"), "utf8")

function stage(name: string) {
  const start = source.indexOf(`<g class="stack-stage" data-layer="${name}">`)
  if (start < 0) throw new Error(`[Sixb] Missing ${name} artwork`)
  const tags = /<\/?g\b[^>]*>/g
  tags.lastIndex = start
  let depth = 0
  for (const match of source.matchAll(tags)) {
    depth += match[0].startsWith("</") ? -1 : 1
    if (depth === 0) return source.slice(start, match.index + match[0].length)
  }
  throw new Error(`[Sixb] Unclosed ${name} artwork`)
}

const layers = [
  {
    name: "connect",
    label: "Connect",
    caption: "Your existing systems",
    x: 12,
    y: 275,
    origin: 650,
  },
  { name: "prepare", label: "Prepare", caption: "Data, ready to use", x: 353, y: 213, origin: 463 },
  { name: "model", label: "Model", caption: "One shared definition", x: 694, y: 151, origin: 265 },
  {
    name: "build",
    label: "Build",
    caption: "Apps, agents, automation",
    x: 1035,
    y: 89,
    origin: 25,
  },
]
const defs = source.match(/<defs>([\s\S]*?)<\/defs>/)?.[1]
if (!defs) throw new Error("[Sixb] Missing illustration definitions")
const stylesStart = css.indexOf(".framework-stack {")
const stylesEnd = css.indexOf(".stack-stage {", stylesStart)
if (stylesStart < 0 || stylesEnd < 0) throw new Error("[Sixb] Missing illustration styles")
const stackStyles = css.slice(stylesStart, stylesEnd)

function stackColors(selector: string) {
  const start = css.indexOf(`${selector} {`)
  const end = css.indexOf("}", start)
  if (start < 0 || end < 0) throw new Error(`[Sixb] Missing ${selector} theme`)
  return Object.fromEntries(
    [...css.slice(start, end).matchAll(/(--stack-[\w-]+):\s*([^;]+);/g)].map((match) => [
      match[1],
      match[2].trim(),
    ])
  )
}

// The illustration inherits its own palette; these three text colors suit GitHub's canvas.
const lightColors = stackColors(".framework-home")
const darkColors = stackColors(".dark .framework-home")
for (const theme of ["light", "dark"]) {
  const dark = theme === "dark"
  const colors: Record<string, string> = {
    ...lightColors,
    ...(dark ? darkColors : {}),
    "--docs-accent": dark ? "#79b1ff" : "#006be6",
    "--foreground": dark ? "#f0f3f6" : "#151719",
    "--muted-foreground": dark ? "#9aa8b9" : "#667384",
  }
  let artwork = `<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="540" viewBox="0 0 1400 540" role="img" aria-labelledby="title desc">
<!-- Generated by apps/docs/src/docs/exportReadmeArchitecture.ts. Do not edit by hand. -->
<title id="title">From your data to your software</title>
<desc id="desc">Connect external systems. Prepare their data. Define a shared domain model. Build apps, agents, and workflows. Actions return to the connected systems.</desc>
<defs>${defs}<marker id="flow-arrow" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0 6 3 0 6Z" fill="var(--docs-accent)"/></marker></defs>
<style>
${stackStyles}
.stack-dataset-shadow{fill:#0f172a;fill-opacity:.06;stroke:none}
.stack-data-row{fill:var(--stack-blue-soft)}
.stack-action-link,.stack-projection,.stack-quote-related{display:none}
.label{font-size:24px;font-weight:600;letter-spacing:-.6px;fill:var(--foreground)}
.caption{font-size:16px;fill:var(--muted-foreground)}
.number{font-size:12px;fill:var(--docs-accent);letter-spacing:1.5px}
</style>
<rect width="1400" height="540" rx="16" fill="${dark ? "#0d1117" : "#f8fafc"}"/>
<g font-family="Arial, Helvetica, sans-serif">
<path d="M257 357C345 357 326 283 410 283M587 295C675 295 657 225 741 225M929 236C1017 236 998 157 1082 157" fill="none" stroke="var(--docs-accent)" stroke-width="1.7" marker-end="url(#flow-arrow)"/>
${layers
  .map(
    (layer, index) => `<g transform="translate(${layer.x} ${layer.y})">
<text class="number" x="20" y="-59">0${index + 1}</text>
<text class="label" x="20" y="-30">${layer.label}</text>
<text class="caption" x="20" y="-7">${layer.caption}</text>
<g class="framework-stack" transform="scale(.68) translate(0 ${-layer.origin})">${stage(layer.name)}</g>
</g>`
  )
  .join("\n")}
<path d="M1305 225C1330 231 1356 234 1356 260V465Q1356 486 1335 486H120Q99 486 99 465V345" fill="none" stroke="var(--docs-accent)" stroke-opacity=".5" stroke-width="1.3" marker-end="url(#flow-arrow)"/>
<rect x="540" y="472" width="320" height="28" fill="${dark ? "#0d1117" : "#f8fafc"}"/>
<text x="700" y="491" text-anchor="middle" class="caption">Actions flow back to your systems</text>
</g></svg>`
  artwork = artwork.replace(/var\((--[\w-]+)\)/g, (_, key) => {
    if (!colors[key]) throw new Error(`[Sixb] Missing color ${key}`)
    return colors[key].replace(/var\(--docs-accent\)/g, colors["--docs-accent"])
  })
  for (const filename of ["pandadoc.png", "pipedrive.png", "companycam.png", "google-drive.svg"]) {
    const buffer = await readFile(resolve(root, `apps/docs/assets/landing/${filename}`))
    const mime = filename.endsWith(".svg") ? "image/svg+xml" : "image/png"
    artwork = artwork.replace(
      `/assets/landing/${filename}`,
      `data:${mime};base64,${buffer.toString("base64")}`
    )
  }
  if (/var\(|href="\//.test(artwork)) throw new Error("[Sixb] Unresolved artwork color or asset")
  await writeFile(resolve(root, `docs/brand/architecture-${theme}.svg`), `${artwork}\n`)
  console.log(`Exported ${theme} architecture`)
}
