import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { createElement } from "react"
import { renderToStaticMarkup } from "react-dom/server"
import { FrameworkStack } from "../components/FrameworkStack"

// Run from the repo root: bun --filter @sixb/docs generate:social
const root = resolve(import.meta.dir, "..")
const css = await readFile(resolve(root, "components/homeWalkthrough.css"), "utf8")
const theme = css.match(/\.framework-home \{([\s\S]*?)\}/)?.[1]
const styles = css.match(/\.framework-stack \{[\s\S]*?(?=\.stack-stage \{)/)?.[0]
if (!theme || !styles) throw new Error("[Sixb] Missing landing illustration styles")
const colors: Record<string, string> = {
  ...Object.fromEntries(
    [...theme.matchAll(/(--stack-[\w-]+):\s*([^;]+);/g)].map((match) => [match[1], match[2].trim()])
  ),
  "--docs-accent": "#006be6",
  "--foreground": "#151719",
  "--muted-foreground": "#667384",
}

let artwork = renderToStaticMarkup(
  createElement(FrameworkStack, { activeLayer: null, phase: "ready" })
)
  .replace(
    'viewBox="0 0 700 830"',
    'xmlns="http://www.w3.org/2000/svg" viewBox="0 0 525 830" width="525" height="830"'
  )
  // Copy is supplied at a readable size by the social card. Keep the artwork's silhouettes.
  .replace(/<text\b[^>]*>[\s\S]*?<\/text>/g, "")
  .replace(
    "<defs>",
    `<defs><style>${styles}
.framework-stack{stroke-width:1.2}
.stack-fine-line,.stack-window{stroke-width:1}
.stack-dataset-shadow{fill:#0f172a;fill-opacity:.06;stroke:none}
.stack-data-row{fill:var(--stack-blue-soft)}
.stack-action-link,.stack-projection{display:none}
</style>`
  )
  .replace(/var\((--[\w-]+)\)/g, (_, key: string) => {
    if (!colors[key]) throw new Error(`[Sixb] Missing social illustration color ${key}`)
    return colors[key]
  })

for (const filename of ["pandadoc.png", "pipedrive.png", "companycam.png", "google-drive.svg"]) {
  const buffer = await readFile(resolve(root, `../assets/landing/${filename}`))
  const mime = filename.endsWith(".svg") ? "image/svg+xml" : "image/png"
  artwork = artwork.replace(
    `/assets/landing/${filename}`,
    `data:${mime};base64,${buffer.toString("base64")}`
  )
}
if (/var\(|href="\//.test(artwork)) throw new Error("[Sixb] Unresolved social artwork asset")
await writeFile(
  resolve(root, "../assets/social-stack.svg"),
  `<!-- Generated by src/docs/exportSocialStack.ts. Do not edit by hand. -->\n${artwork}\n`
)
console.log("Exported social stack")
