/** Old bookmarked sections that moved to a dedicated guide. Page redirects preserve their hash. */
export const legacySections: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "/connectors": {
    "define-an-oauth-connector": "/connectors/authentication#configure-a-connector",
    "protect-oauth-credentials": "/connectors/authentication#configure-a-connector",
    "connect-an-oauth-account-from-an-app": "/connectors/authentication#connect-an-account",
    connectorcontext: "/connectors#custom-connectors",
    "custom-clients": "/connectors#custom-connectors",
    "built-in-adapters": "/connectors/library",
    restoptions: "/connectors/library",
    "sqlconnection-and-sftpconnection-options": "/connectors/library",
    "hosted-service-connectors": "/connectors/library",
    webhooks: "/connectors/webhooks",
    "webhooks-updating-source-datasets": "/connectors/webhooks#define-a-webhook",
  },
  "/connectors/library": {
    "protocol-adapters": "/connectors/library",
    restoptions: "/connectors/library",
    "sqlconnection-and-sftpconnection-options": "/connectors/library",
  },
  "/connectors/authentication": {
    "define-an-oauth-connector": "/connectors/authentication#configure-a-connector",
    "protect-oauth-credentials": "/connectors/authentication#configure-a-connector",
    "connect-an-oauth-account-from-an-app": "/connectors/authentication#connect-an-account",
  },
  "/connectors/webhooks": {
    "webhooks-updating-source-datasets": "/connectors/webhooks#define-a-webhook",
    "managed-oauth-webhooks": "/connectors/webhooks#oauth-accounts",
    "ingest-source-changes": "/datasets/ingestion",
    "ingestion-recovery": "/datasets/ingestion#recovery",
    "objects-and-relationships": "/datasets/ingestion#objects-and-relationships",
  },
  "/datasets": {
    "source-ordering": "/datasets/source-ordering",
    "merge-behavior": "/datasets/source-ordering#merge-behavior",
    "sequence-values": "/datasets/source-ordering#sequence-values",
    "v1-constraints": "/datasets/source-ordering#v1-constraints",
    "ingest-source-changes": "/datasets/ingestion",
    "ingestion-recovery": "/datasets/ingestion#recovery",
    "objects-and-relationships": "/datasets/ingestion#objects-and-relationships",
  },
  "/syncs": {
    "incremental-syncs-with-checkpoints": "/syncs/incremental#save-a-checkpoint",
    "merge-source-requirements": "/syncs/incremental#source-requirements",
    "oauth-connector-fan-out": "/syncs#sync-connected-accounts",
    "sync-modes": "/syncs#choose-a-sync-mode",
    "ingesting-files": "/syncs#import-files",
    schedules: "/schedules",
  },
  "/syncs/incremental": {
    "incremental-syncs-with-checkpoints": "/syncs/incremental#save-a-checkpoint",
    "merge-changes": "/syncs/incremental#update-and-delete-records",
    "merge-source-requirements": "/syncs/incremental#source-requirements",
  },
  "/pipelines": {
    schedules: "/schedules",
    "running-pipelines": "/deployment#start-services",
  },
  "/projections": {
    "running-projections": "/deployment#start-services",
  },
  "/objects": {
    "mental-model": "/objects",
    "collection-methods": "/objects#create-or-update-an-object",
    upsert: "/objects#create-or-update-an-object",
    "merge-semantics": "/objects#create-or-update-an-object",
    "batch-writes": "/objects#create-or-update-an-object",
    "dates-are-normalized": "/objects#create-or-update-an-object",
    get: "/objects#read-an-object",
    list: "/objects#list-objects",
    "list-vs-query": "/objects#list-objects",
    "byidid-handle": "/objects#add-or-remove-relationships",
    "the-byid-handle": "/objects#add-or-remove-relationships",
    links: "/objects#add-or-remove-relationships",
    "writing-inside-an-action": "/actions",
    requestaction: "/actions#use-your-action",
    appendtelemetrybatch: "/objects/telemetry#append-in-batch",
    events: "/websockets",
    "in-this-section": "/objects",
    related: "/objects",
  },
  "/objects/querying": {
    "terminal-methods": "/objects/querying#filter-objects",
    list: "/objects/querying#filter-objects",
    "count-and-exists": "/objects/querying#count-and-group-results",
    facets: "/objects/querying#count-and-group-results",
    predicates: "/objects/querying#filter-objects",
    "combining-with-and-or-not": "/objects/querying#filter-objects",
    "null-and-missing-values": "/objects/querying#filter-objects",
    "text-search": "/objects/querying#search-text",
    relevance: "/objects/querying#search-text",
    "traversing-links": "/objects/querying#follow-relationships",
    "expanding-links": "/objects/querying#include-related-objects",
    "sorting-and-limits": "/objects/querying#sort-and-paginate",
    "validate-and-explain": "/objects/querying",
    "how-metadata-drives-queries": "/ontology/properties#enable-queries",
    related: "/objects/querying",
  },
  "/objects/telemetry": {
    "declare-a-telemetry-property": "/objects/telemetry#define-a-telemetry-property",
    "identity-series-at": "/objects/telemetry#append-a-point",
    "read-history-and-latest": "/objects/telemetry#read-history",
    "over-http": "/server#explore-the-api",
    "the-telemetryappended-event": "/websockets",
    related: "/objects/telemetry",
  },
  "/server/object-queries": {
    "raw-query-json": "/server/object-queries#send-a-query",
    "exact-object-references": "/server/object-queries#select-known-objects",
    "querying-physical-links": "/server/object-queries#read-link-records",
    "count-exists-and-facets": "/server/object-queries#group-counts",
    "page-tokens": "/server/object-queries#paginate-results",
    "expanding-links": "/server/object-queries#read-relationships",
    "node-reference": "/server/object-queries#query-nodes",
    "predicate-shapes": "/server/object-queries#predicates",
    "calling-a-route": "/server/object-queries#send-a-query",
    "provider-support": "/server/object-queries#query-nodes",
    related: "/server/object-queries",
  },
  "/actions": {
    "the-builder": "/actions#define-an-action",
    bindings: "/actions#define-an-action",
    params: "/actions#parameters",
    "execution-model": "/actions#call-external-systems",
    "phase-contexts": "/actions#call-external-systems",
    "reading-telemetry-in-actions": "/objects/telemetry#read-history",
    "editing-objects": "/actions#edit-objects-and-relationships",
    "reassigning-a-cardinality-one-link": "/actions#edit-objects-and-relationships",
    "requesting-actions": "/actions#use-your-action",
    "run-an-action": "/actions#use-your-action",
    "run-lifecycle-and-events": "/actions#use-your-action",
    related: "/actions",
  },
  "/workflows": {
    "when-to-use-a-workflow": "/workflows",
    "define-steps": "/workflows#define-a-workflow",
    "compose-the-chain": "/workflows#define-a-workflow",
    "pass-data-between-nodes": "/workflows#pass-data-between-steps",
    "action-nodes": "/workflows#run-an-action",
    "call-a-model-from-a-step": "/models/generation#in-a-workflow",
    "define-agent-tasks": "/workflows#add-an-ai-task",
    "pause-for-a-human-with-interventions": "/workflows/interventions",
    "start-a-run": "/workflows#start-a-workflow",
    "start-from-a-schedule": "/workflows#start-a-workflow",
    "bind-to-an-event-schedule": "/workflows#start-a-workflow",
    "run-lifecycle": "/workflows#define-a-workflow",
    "run-locally-or-in-production": "/deployment#start-services",
    related: "/workflows",
  },
  "/workflows/interventions": {
    "defining-an-intervention": "/workflows/interventions#define-an-intervention",
    "response-fields": "/workflows/interventions#define-an-intervention",
    defaults: "/workflows/interventions#define-an-intervention",
    "placing-an-intervention-in-a-workflow": "/workflows/interventions#add-it-to-a-workflow",
    "lifecycle-waiting-submit-resume": "/workflows/interventions#add-it-to-a-workflow",
    "lifecycle-events": "/websockets",
    "resolving-interventions-http": "/workflows/interventions#submit-a-response",
    "submitting-a-response": "/workflows/interventions#submit-a-response",
    related: "/workflows/interventions",
  },
  "/rules": {
    "compose-conditions": "/rules#combine-conditions",
    predicates: "/rules#combine-conditions",
    "how-matching-works": "/rules#define-a-rule",
    "reacting-to-the-signal": "/rules#start-a-workflow",
    "file-location": "/rules#define-a-rule",
    "rule-vs-workflow": "/rules#start-a-workflow",
    notes: "/rules#define-a-rule",
    related: "/rules#start-a-workflow",
  },
  "/models": {
    "generate-a-response": "/models/generation#in-a-workflow",
    "start-a-conversation": "/models#use-in-your-app",
    "add-the-chat-ui": "/models#use-in-your-app",
    "conversation-behavior": "/models#built-in-agent",
    "ai-in-workflows": "/workflows#add-an-ai-task",
    "next-steps": "/models",
  },
  "/models/configuration": {
    "configure-models": "/models#configure-a-model",
    "model-selection": "/models/generation#choose-a-model",
    "custom-credentials": "/models/configuration",
    "capabilities-and-output-limits": "/models/generation#choose-a-model",
  },
  "/models/generation": {
    text: "/models/generation#in-a-workflow",
    "existing-messages": "/models/generation",
    controls: "/models/generation#choose-a-model",
    result: "/models/generation#usage",
    "in-an-action": "/actions#call-external-systems",
    "execution-context": "/models/generation#in-a-workflow",
  },
  "/models/tools-and-authorization": {
    "custom-tools": "/models/tools-and-authorization#define-a-tool",
    "files-from-tools": "/models/tools-and-authorization#define-a-tool",
    "exa-web-tools": "/connectors/library",
    skills: "/models/tools-and-authorization#add-a-skill",
    "sandbox-tools": "/sandboxes",
    authorization: "/models#built-in-agent",
    "workflow-tools-and-groups": "/workflows#add-an-ai-task",
    "gateway-access": "/models#built-in-agent",
  },
  "/models/usage-and-limits": {
    "automatic-accounting": "/models/usage-and-limits#view-usage",
    "inspect-usage": "/models/usage-and-limits#view-usage",
    "monthly-limits": "/models/usage-and-limits#set-a-monthly-limit",
    "admission-and-failures": "/models/usage-and-limits#set-a-monthly-limit",
    "accounting-behavior": "/models/usage-and-limits#view-usage",
    recovery: "/models/usage-and-limits#embeddings",
  },
  "/sandboxes": {
    "runtime-requirements": "/sandboxes#providers",
    wiring: "/sandboxes#configure-a-sandbox",
    "network-policy": "/sandboxes#providers",
    lifecycle: "/sandboxes#configure-a-sandbox",
    "choosing-a-provider": "/sandboxes#providers",
    related: "/sandboxes#providers",
    "optional-filesystem-persistence": "/sandboxes#providers",
  },
  "/apps": {
    "mental-model": "/apps#create-a-page",
    "public-environment-variables": "/apps/customization#public-environment-variables",
    "file-based-routing": "/apps#add-routes",
    navigation: "/apps#add-routes",
    "shared-access-uses-ordinary-pages": "/auth/shared-access",
    "layouts-and-metadata": "/apps#add-a-layout",
    "pwa-assets-and-standalone-layout": "/apps/customization#app-icons",
    "styles-and-theming": "/apps#add-styles",
    "ui-packages": "/apps#add-styles",
    "custom-login-experience": "/apps/customization#custom-sign-in",
    running: "/apps#create-a-page",
    next: "/apps#add-assets",
  },
  "/apps/querying-data": {
    "typed-queries-with-hooks": "/apps/querying-data#display-objects",
    "app-hooks": "/client/typed-queries#react-hooks",
    "importing-ontology-types": "/client/typed-queries#browser-safe-ontology-imports",
    "typed-vs-untyped": "/client/typed-queries",
    "expanding-related-objects": "/objects/querying#include-related-objects",
    "invalidating-after-actions": "/apps/actions#refresh-data",
    related: "/apps/querying-data",
  },
  "/apps/actions": {
    "recommended-button-flow": "/apps/actions#run-an-action",
    "object-and-global-actions": "/apps/actions#run-a-global-action",
    "high-frequency-controls": "/apps/actions",
    "enqueue-only-vs-terminal-mutations": "/apps/actions#refresh-data",
    "react-free-waiting": "/client#call-the-api",
    "scoped-action-events": "/client/events",
    "manual-invalidation": "/client/typed-queries#refresh-cached-data",
    related: "/apps/actions",
  },
  "/ontology/properties": {
    "object-type-search-profile": "/ontology/properties#configure-search",
    "how-metadata-drives-queries": "/ontology/properties#enable-queries",
    "prop-signature": "/ontology/properties#define-a-property",
    options: "/ontology/properties#required-and-nullable-values",
    "schema-forms": "/ontology/properties#choose-a-schema",
    "modeling-money": "/ontology/properties#choose-a-schema",
    "static-vs-telemetry-mode": "/ontology/properties#record-history",
    "keep-properties-shallow": "/ontology/properties#structured-values",
    "property-query-metadata": "/ontology/properties#enable-queries",
    "which-schemas-support-which-flag": "/ontology/properties#enable-queries",
    related: "/ontology/properties",
  },
  "/ontology/value-types": {
    "inheritance-with-extends": "/ontology/object-types#extend-a-type",
    "extends-vs-parents": "/ontology/object-types#extend-a-type",
    "value-types": "/ontology/value-types#define-a-value-type",
    "definevaluetype-fields": "/ontology/value-types#define-a-value-type",
    "referencing-with-valuetyperef": "/ontology/value-types#use-it-in-a-property",
    interfaces: "/ontology/object-types",
    "implementing-an-interface": "/ontology/object-types",
    "choosing-between-them": "/ontology/value-types#use-it-in-a-property",
    related: "/ontology/value-types",
  },
  "/auth/authentication": {
    "pick-a-strategy": "/auth/authentication#configure-sign-in",
    "magic-link-options": "/auth/authentication#configure-sign-in",
    "oidc-options": "/auth/authentication#configure-sign-in",
    "auth-needs-storage": "/auth/authentication#sessions",
    "allowed-domains-and-bootstrap": "/auth/authentication#set-up-the-first-administrator",
    "invitations-and-members": "/auth/members#manage-members",
    "sessions-and-cookies": "/auth/authentication#sessions",
    behavior: "/auth/authentication#sessions",
    "programmatic-access": "/auth/members#service-accounts-and-tokens",
    "sign-in-endpoints": "/server#explore-the-api",
    "from-sign-in-to-authorization": "/auth/authorization",
    next: "/auth/authentication",
    "the-two-layers": "/auth/authorization",
    "how-they-connect": "/auth/authorization",
    bootstrap: "/auth/authentication#set-up-the-first-administrator",
  },
  "/auth/authorization": {
    grants: "/auth/authorization#choose-permissions",
    "selecting-definitions": "/auth/authorization#choose-permissions",
    "shared-access": "/auth/shared-access",
    "broad-grants": "/auth/authorization#choose-permissions",
    "application-access": "/auth/authorization#control-application-access",
    "membership-policies": "/auth/members#manage-members",
    "asking-what-a-caller-may-administer": "/auth/members#manage-members",
    "how-principals-join-groups": "/auth/members",
    "how-grants-are-enforced": "/auth/authorization#permissions-during-execution",
    "protected-sdk-surface": "/auth/authorization#permissions-during-execution",
    "why-writing-needs-the-read-grant-too": "/auth/authorization#choose-permissions",
    "event-visibility": "/websockets#domain-events",
    "with-the-server": "/server#authenticate-a-request",
    "file-location": "/auth/authorization#define-a-group",
    "how-to-model-authorization": "/auth/authorization#define-a-role",
    related: "/auth/authorization",
  },
  "/runtime": {
    "optional-configuration": "/runtime#optional-services",
    "start-the-project": "/cli#project-commands",
    next: "/runtime",
  },
  "/errors": {
    "failure-records": "/errors#run-failures",
    "failure-notifications": "/logging#report-failures",
  },
  "/infrastructure": {
    "the-three-storage-slots": "/infrastructure#object-storage",
    "events-and-background-jobs": "/infrastructure#events-and-jobs",
    "existing-data": "/infrastructure#choose-a-production-setup",
    retention: "/infrastructure#choose-a-production-setup",
    "provider-matrix": "/infrastructure#object-storage",
    "production-configuration": "/infrastructure#choose-a-production-setup",
    migrations: "/deployment#migrations",
    related: "/infrastructure",
  },
  "/deployment": {
    "dev-vs-production": "/deployment#prepare-your-configuration",
    "role-commands": "/deployment#start-services",
    "public-origins": "/deployment#configure-public-origins",
    "storage-migrations": "/deployment#migrations",
    "background-work-and-recovery": "/deployment#scaling-and-health",
    "startup-order": "/deployment#start-services",
    "atlas-admin-ui": "/deployment#start-services",
    "a-minimal-production-topology": "/deployment#start-services",
    "scaling-roles": "/deployment#scaling-and-health",
    related: "/deployment",
  },
  "/logging": {
    "logging-from-a-handler": "/logging#write-a-log",
    "reading-logs-in-code": "/client#read-run-logs",
    "reading-logs-in-an-app": "/client#read-run-logs",
    "the-atlas-logs-page": "/logging#view-logs",
    configuration: "/logging#configure-output",
    "output-providers": "/logging#configure-output",
    lifecycle: "/logging#configure-output",
    related: "/logging",
  },
  "/testing": {
    "run-a-test": "/testing#test-application-behavior",
    "in-memory-providers-as-fixtures": "/testing#create-a-fixture",
    "temp-dirs-and-fixed-timestamps": "/testing#integration-tests",
    "authorization-testing": "/testing#test-permissions",
    "clientserver-e2e": "/testing#integration-tests",
    related: "/testing",
  },
  "/websockets": {
    "event-catalog": "/websockets#domain-events",
    "event-envelope": "/websockets#domain-events",
    "reading-events": "/websockets#replay-events",
    "subscribing-to-events": "/websockets#domain-events",
    "appending-events": "/schedules#run-on-an-event",
    "http-get-apievents": "/server#explore-the-api",
    webhooks: "/connectors/webhooks",
    "dispatch-lifecycle": "/connectors/webhooks",
    related: "/websockets",
  },
  "/client": {
    "mental-model": "/client#configure-a-client",
    "subpath-map": "/client#choose-an-import",
    "root-generated-sdk": "/client#call-the-api",
    "rendering-object-files": "/client#display-files",
    "query-typed-object-queries": "/client/typed-queries",
    "hooks-tanstack-query": "/client/typed-queries#react-hooks",
    "action-run-mutations": "/apps/actions",
    "events-live-websocket": "/client/events",
    "browser-auth-bootstrap": "/client#standalone-browser-apps",
    "models-ids-and-ui-shapes": "/client#call-the-api",
    "which-subpath-to-use": "/client#choose-an-import",
    related: "/client",
  },
  "/client/typed-queries": {
    "builder-over-http": "/client/typed-queries#query-objects",
    "expanding-links": "/client/typed-queries#query-objects",
    "hook-options": "/client/typed-queries#react-hooks",
    "shared-queries": "/client/typed-queries#reuse-queries",
    "query-keys-and-invalidation": "/client/typed-queries#refresh-cached-data",
    "transport-overrides": "/client/typed-queries#client-overrides",
    errors: "/client/typed-queries#query-errors",
    related: "/client/typed-queries",
  },
  "/client/events": {
    "event-builders": "/client/events#filter-events",
    useevents: "/client/events#subscribe-to-changes",
    "latest-telemetry": "/client/events#read-live-telemetry",
    "invalidate-on-events": "/client/events#refresh-queries",
    related: "/client/events",
  },
  "/server": {
    "starting-the-server": "/server#custom-server-setup",
    options: "/server#custom-server-setup",
    "route-groups": "/server#explore-the-api",
    "real-time-events": "/websockets",
    openapi: "/server#explore-the-api",
    "auth-csrf-and-cookies": "/server#authenticate-a-request",
    "admin-ui-atlas-vs-custom-apps": "/deployment#start-services",
    related: "/server",
  },
  "/ontology": {
    "why-model-an-ontology": "/ontology#bring-the-model-to-life",
    "core-terms": "/ontology#define-your-model",
    "defining-a-type": "/ontology#define-your-model",
    "refer-to-properties-and-links": "/ontology/object-types#reference-properties-and-links",
    "modeling-money-and-telemetry": "/ontology/properties",
    "file-location": "/ontology#define-your-model",
    "how-to-model-your-domain": "/ontology#define-your-model",
    "in-this-section": "/ontology",
  },
  "/ontology/units-and-semantics": {
    semantictype: "/ontology/units-and-semantics#define-a-measurement",
    "how-units-validate-telemetry": "/ontology/units-and-semantics#supply-a-unit",
    "the-quantitative-types-catalog": "/ontology/units-and-semantics#find-available-units",
    "units-api": "/ontology/units-and-semantics#find-available-units",
    related: "/ontology/units-and-semantics",
  },
  "/ontology/object-types": {
    defineobjecttype: "/ontology/object-types#define-a-type",
    "the-primary-property-rule": "/ontology/object-types#give-objects-an-identity",
    links: "/ontology/links",
    "object-type-search-profile": "/ontology/properties#configure-search",
    "named-vector-profiles": "/ontology/properties#configure-vector-search",
    "extends-inheritance": "/ontology/object-types#extend-a-type",
    "file-location": "/ontology/object-types#define-a-type",
    "use-the-object-type": "/objects",
    related: "/ontology/object-types",
  },
  "/ontology/links": {
    "declare-a-link": "/ontology/links#define-a-link",
    "link-forms": "/ontology/links#other-targets",
    "link-parameters": "/ontology/links#define-a-link",
    "target-forms": "/ontology/links#other-targets",
    cardinality: "/ontology/links#choose-cardinality",
    "link-properties": "/ontology/links#add-relationship-properties",
    "create-and-remove-links": "/objects#add-or-remove-relationships",
    "list-links-from-an-object": "/objects#add-or-remove-relationships",
    "traverse-links-in-queries": "/objects/querying#follow-relationships",
    "inherited-links": "/ontology/object-types#extend-a-type",
    related: "/ontology/links",
  },
  "/examples": {
    "northline-the-operations-reference": "/examples#northline",
    "auth-authentication-and-access-control": "/examples#authentication-permissions",
    next: "/get-started",
  },
}
