import type { DeployRelease } from "@sixb/core/deploy"
import type { DeploymentLayout } from "./layout"
import type { ProcessManifest } from "./server/manifest"
import { shellQuote } from "./shell"
import { renderUpdatePage } from "./update-page"

const GENERATED = "Generated by sixb deploy. Changes are replaced on the next deploy."

/** The supervisor's view of the release: absolute commands, full environments. */
export function renderProcessManifest(
  release: DeployRelease,
  layout: DeploymentLayout
): ProcessManifest {
  const sixb = `${layout.project}/node_modules/.bin/sixb`
  return {
    version: 1,
    name: release.name,
    cwd: layout.project,
    runDir: layout.runDir,
    logDir: layout.logDir,
    releasePath: layout.releaseRecord,
    services: release.services.map((service) => ({
      name: service.name,
      processName: `${release.name}-${service.name}`,
      command: layout.bun,
      args:
        service.command.program === "sixb"
          ? [sixb, ...service.command.args]
          : [...service.command.args],
      env: service.env,
      instances: service.instances,
      killTimeoutMs: service.process.killTimeoutMs,
      restartDelayMs: service.process.restartDelayMs,
      ...(service.process.maxMemory ? { maxMemory: service.process.maxMemory } : {}),
    })),
  }
}

/** Pins the server half of this package to the project's Bun and manifest. */
export function renderCtl(layout: DeploymentLayout): string {
  return [
    "#!/bin/sh",
    `# ${GENERATED}`,
    `exec ${shellQuote(layout.bun)} ${shellQuote(`${layout.project}/node_modules/.bin/sixb-deploy-ssh`)} "$@" --manifest ${shellQuote(layout.manifest)}`,
    "",
  ].join("\n")
}

/**
 * The deployment's `systemd --user` unit. Linger starts the user's systemd at boot, so the
 * unit comes back after a reboot without anyone logged in.
 */
export function renderUnit(release: DeployRelease, layout: DeploymentLayout): string {
  // Long enough for the supervisor to stop every process with its own kill timeout.
  const stopSeconds =
    Math.ceil(
      Math.max(...release.services.map((service) => service.process.killTimeoutMs)) / 1000
    ) + 10
  return [
    `# ${GENERATED}`,
    "[Unit]",
    `Description=Sixb deployment ${release.name}`,
    "",
    "[Service]",
    "Type=simple",
    `WorkingDirectory=${systemdValue(layout.project)}`,
    `Environment=${systemdValue(`PATH=${layout.bunDir}:/usr/local/bin:/usr/bin:/bin`)}`,
    `ExecStart=${systemdValue(layout.ctl)} supervise`,
    "Restart=always",
    "RestartSec=2",
    "KillSignal=SIGTERM",
    `TimeoutStopSec=${stopSeconds}`,
    "",
    "[Install]",
    "WantedBy=default.target",
    "",
  ].join("\n")
}

/** One site per HTTP service, forwarded to the service's loopback port. */
export function renderCaddySnippet(release: DeployRelease): string {
  const sites = release.services.flatMap((service) => {
    if (!service.http) return []
    const pages = service.name === "app" || service.name === "atlas"
    return [
      [
        `${service.http.domain} {`,
        `\treverse_proxy ${service.http.host}:${service.http.port}`,
        ...(pages ? updatePageOnProxyErrors() : []),
        "}",
      ].join("\n"),
    ]
  })
  return [`# ${GENERATED}`, "", sites.join("\n\n"), ""].join("\n")
}

/**
 * While the app or Atlas is down — during a deploy, or an outage — a browser asking for a page
 * gets the update page instead of Caddy's bare error. Other requests keep the error.
 */
function updatePageOnProxyErrors(): string[] {
  return [
    "\thandle_errors 502 503 504 {",
    "\t\t@page {",
    "\t\t\tmethod GET",
    "\t\t\theader Accept *text/html*",
    "\t\t}",
    "\t\thandle @page {",
    '\t\t\theader Content-Type "text/html; charset=utf-8"',
    '\t\t\theader Cache-Control "no-store"',
    '\t\t\theader Retry-After "10"',
    "\t\t\trespond 503 {",
    "\t\t\t\tbody <<HTML",
    ...renderUpdatePage()
      .split("\n")
      .map((line) => `\t\t\t\t${line}`),
    "\t\t\t\tHTML",
    "\t\t\t}",
    "\t\t}",
    "\t\thandle {",
    '\t\t\trespond "Service temporarily unavailable" {err.status_code}',
    "\t\t}",
    "\t}",
  ]
}

function systemdValue(value: string): string {
  return value.replace(/%/g, "%%").replace(/\s/g, "\\x20")
}
