import { Buffer } from "node:buffer"
import { deflateSync } from "node:zlib"
import type { BlobStorage, FileRef } from "@sixb/core"

type SampleBlobStorage = Pick<BlobStorage, "put">

interface SampleAttachment {
  readonly fileName: string
  readonly mediaType: string
  readonly logicalPath: string
  readonly body: () => Uint8Array
}

const attachmentsByDocumentId: Record<string, SampleAttachment> = {
  "doc-techstart-proposal": {
    fileName: "techstart-platform-proposal.pdf",
    mediaType: "application/pdf",
    logicalPath: "acme-erp/documents/techstart-platform-proposal.pdf",
    body: () =>
      createPdf({
        title: "TechStart Platform Proposal",
        subtitle: "Acme Corp ERP sample document",
        lines: [
          "Scope: customer portal, billing integration, and launch support.",
          "Status: approved for implementation.",
          "This PDF is generated by the Acme ERP sync and stored as a Sixb FileRef.",
        ],
      }),
  },
  "doc-greenenergy-spec": {
    fileName: "greenenergy-dashboard-preview.png",
    mediaType: "image/png",
    logicalPath: "acme-erp/documents/greenenergy-dashboard-preview.png",
    body: createDashboardPreviewPng,
  },
}

export async function createSampleAttachmentForDocument(
  blobs: SampleBlobStorage,
  documentId: string
): Promise<FileRef | undefined> {
  const attachment = attachmentsByDocumentId[documentId]
  if (!attachment) {
    return undefined
  }

  return blobs.put({
    body: attachment.body(),
    fileName: attachment.fileName,
    mediaType: attachment.mediaType,
    logicalPath: attachment.logicalPath,
  })
}

function createPdf(input: {
  readonly title: string
  readonly subtitle: string
  readonly lines: readonly string[]
}): Uint8Array {
  const content = [
    "BT",
    "/F1 22 Tf",
    "72 730 Td",
    `(${escapePdfText(input.title)}) Tj`,
    "/F1 12 Tf",
    "0 -30 Td",
    `(${escapePdfText(input.subtitle)}) Tj`,
    ...input.lines.flatMap((line) => ["0 -24 Td", `(${escapePdfText(line)}) Tj`]),
    "ET",
  ].join("\n")

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,
  ]

  let pdf = "%PDF-1.4\n"
  const offsets = [0]
  for (const [index, body] of objects.entries()) {
    offsets.push(Buffer.byteLength(pdf))
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`
  }

  const xrefOffset = Buffer.byteLength(pdf)
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += "0000000000 65535 f \n"
  for (const offset of offsets.slice(1)) {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`
  pdf += `startxref\n${xrefOffset}\n%%EOF\n`

  return new TextEncoder().encode(pdf)
}

function escapePdfText(value: string): string {
  return value.replace(/[\\()]/g, "\\$&")
}

function createDashboardPreviewPng(): Uint8Array {
  const width = 320
  const height = 180
  const bytesPerPixel = 4
  const rowSize = width * bytesPerPixel + 1
  const raw = Buffer.alloc(rowSize * height)

  for (let y = 0; y < height; y += 1) {
    const rowOffset = y * rowSize
    raw[rowOffset] = 0
    for (let x = 0; x < width; x += 1) {
      const inCard = x >= 20 && x < 300 && y >= 20 && y < 160
      const inHeader = x >= 20 && x < 300 && y >= 20 && y < 52
      const barIndex = Math.floor((x - 44) / 42)
      const barHeight = [34, 58, 42, 76, 64, 92][barIndex] ?? 0
      const inBar = x >= 44 && x < 286 && y >= 142 - barHeight && y < 142 && (x - 44) % 42 < 24

      if (inHeader) {
        setPixel(raw, rowOffset, x, 18, 96, 160)
      } else if (inBar) {
        setPixel(raw, rowOffset, x, 44, 180, 132)
      } else if (inCard) {
        setPixel(raw, rowOffset, x, 248, 250, 252)
      } else {
        setPixel(raw, rowOffset, x, 232, 238, 245)
      }
    }
  }

  return createPng(width, height, raw)
}

function setPixel(
  raw: Buffer,
  rowOffset: number,
  x: number,
  red: number,
  green: number,
  blue: number
): void {
  const offset = rowOffset + 1 + x * 4
  raw[offset] = red
  raw[offset + 1] = green
  raw[offset + 2] = blue
  raw[offset + 3] = 255
}

function createPng(width: number, height: number, rawRgbaRows: Buffer): Uint8Array {
  const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(width, 0)
  ihdr.writeUInt32BE(height, 4)
  ihdr[8] = 8
  ihdr[9] = 6
  ihdr[10] = 0
  ihdr[11] = 0
  ihdr[12] = 0

  return Buffer.concat([
    signature,
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", deflateSync(rawRgbaRows)),
    pngChunk("IEND", Buffer.alloc(0)),
  ])
}

function pngChunk(type: string, data: Buffer): Buffer {
  const typeBytes = Buffer.from(type, "ascii")
  const chunk = Buffer.alloc(12 + data.length)
  chunk.writeUInt32BE(data.length, 0)
  typeBytes.copy(chunk, 4)
  data.copy(chunk, 8)
  chunk.writeUInt32BE(crc32(Buffer.concat([typeBytes, data])), chunk.length - 4)
  return chunk
}

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff
  for (const byte of bytes) {
    crc ^= byte
    for (let bit = 0; bit < 8; bit += 1) {
      crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1
    }
  }
  return (crc ^ 0xffffffff) >>> 0
}
